### ISSUE TITLE
ssl設定が効かない

### ISSUE THREAD

**Issue by ghost** [val00250/webui#1]
V3で利用した際に路線図へのssl設定が効かなかったので修正したら治りました。
https://github.com/val00250/webui/blob/master/expGuiMap/expGuiMap.js#L2138

修正前

```
    } else if (String(name).toLowerCase() == String("ssl").toLowerCase()) {
```

修正後

```
    } else if (type == 'ssl') {
```

プルリク出そうとpush試みたけど403エラー出てよくわからんのでIssue登録とします。

**Comment by val00250** [comment]
恥ずかしいミスをしてしまいました。
また、大文字小文字の設定もミスしていたので、修正しました。

**Comment by ghost** [comment]
![寿司ゆき:XD](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/77.png)
